---
- hosts: all
  become: true
  tasks:
   - name: updateing The cache
     apt:
       update_cache: yes
   - name: installing common software
     apt:
      name: software-properties-common
      state: latest
   - name: Add PHP 7 PPA repository
     apt_repository:
      repo: 'ppa:ondrej/php'
   - name: Install PHP packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'php7.3-common', 'php7.3-mysql', 'php7.3-xml', 'php7.3-curl', 'php7.3-gd', 'php7.3-imagick','php7.3-cli','php7.3-dev','php7.3-imap','php7.3-mbstring','php7.3-zip','php7.3-fpm','php7.3-intl','php7.3-soap']
