---

- hosts: all
  become: true
  vars_prompt:
      - name: "host"
        prompt: "please enter your FQDN(domain name)"
        private: no
      - name: "branch"
        prompt: "Which branch you want deploy?"
        private: no

  vars_files:
        - "./vars/input.yml"
  roles:
    - permissions
    - git
    - php7.3
    - nginx
    - mysql
  tasks:
     - name: restarting php-fpm and nginx
       command: systemctl restart {{item}}
       with_items:
             - nginx
             - php7.3-fpm


