- name: Installing git on server
  apt:
    update_cache: yes
    name: git
    state: latest    
- name: cloning repo
  git: 
   repo: "https://{{ gitlabuser | urlencode }}:{{ gitlabpassword | urlencode }}@gitlab.com/<url>"
   dest: /var/www/lets_eduvate
   force: yes
   version: "{{branch}}"
 
  
